FROM taichangzhou/vllm-omni-ci:v0.16.0_cuda_12.8
ARG APP_DIR=/workspace/vllm-omni
WORKDIR ${APP_DIR}

COPY . .

RUN uv pip install --system --no-cache-dir ".[dev]"

RUN ln -sf /usr/bin/python3 /usr/bin/python

ENTRYPOINT []
